### ISSUE TITLE
Update CONTRIBUTING.md to clarify need for tests for library modules

### ISSUE THREAD

**Issue by clynnes** [nasa/eo-metadata-tools#10]
**Describe the bug**
CONTRIBUTING.md implies that every contribution needs a test. However, including tests for Jupyter notebooks is problematic, there being no consensus in the community as to how to do it properly.

**To Reproduce**
Inspection of CONTRIBUTING.md.

**Expected behavior**
Expected to see which cases require test inclusion.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:: Mac OS X
 - Browser: All
 - Version: All

**Additional context**
N/A

**Comment by clynnes** [comment]
Suggest for clarity, the statement about including tests be qualified to "for library modules"

**Comment by jceaser** [comment]
How does it sound to state that any code packaged into a python module (or similar packaging depending on language) and intended to be linkable requires tests? Utility scripts, example scripts, experimental code, and Notebooks do not need tests.

**Comment by clynnes** [comment]
That works

**Comment by jceaser** [comment]
Having people look at the change now.
